const defaultSettings={name:'কাছেপাই',slogan:'আপনার প্রয়োজন, হাতের কাছেই।',logo:'',hero:'আপনার প্রয়োজন, হাতের কাছেই।',heroText:'সহজে খুঁজুন, পছন্দ করুন, অর্ডার করুন।',payments:{'Cash on Delivery':true,'bKash':true,'Nagad':true,'Rocket':true,'Upay':true,'Card':true,'Send Money':true,'Bank':true}};
const products=[
{id:1,name:'প্রিমিয়াম কটন টি-শার্ট',cat:'ফ্যাশন',price:450,old:600,stock:18,img:'',emoji:'👕'},
{id:2,name:'কিচেন রাইস কুকার',cat:'ইলেকট্রনিক্স',price:1850,old:2200,stock:7,img:'',emoji:'🍚'},
{id:3,name:'স্টিল ওয়াটার বোতল',cat:'হোম',price:380,old:450,stock:25,img:'',emoji:'🥤'},
{id:4,name:'স্কিন কেয়ার ফেসওয়াশ',cat:'বিউটি',price:290,old:350,stock:12,img:'',emoji:'🧴'},
{id:5,name:'শিশুদের স্কুল ব্যাগ',cat:'বাচ্চাদের',price:750,old:900,stock:9,img:'',emoji:'🎒'},
{id:6,name:'USB LED ডেস্ক ল্যাম্প',cat:'ইলেকট্রনিক্স',price:520,old:650,stock:14,img:'',emoji:'💡'}];
let settings=JSON.parse(localStorage.getItem('kp_settings')||'null')||defaultSettings;let cart=JSON.parse(localStorage.getItem('kp_cart')||'[]');let wish=JSON.parse(localStorage.getItem('kp_wish')||'[]');let currentCat='সব';
function money(n){return Number(n).toLocaleString('bn-BD')}
function init(){document.getElementById('storeName').textContent=settings.name;document.getElementById('slogan').textContent=settings.slogan;document.getElementById('heroTitle').textContent=settings.hero;document.getElementById('heroText').textContent=settings.heroText;if(settings.logo)document.getElementById('logoBox').innerHTML=`<img src="${settings.logo}" alt="logo">`;renderCats();render();updateCart();}
function renderCats(){let cats=['সব',...new Set(products.map(p=>p.cat))];document.getElementById('cats').innerHTML=cats.map(c=>`<button onclick="currentCat='${c}';render()">${c}</button>`).join('')}
function render(){let q=document.getElementById('search').value.toLowerCase();let a=products.filter(p=>(currentCat==='সব'||p.cat===currentCat)&&(p.name.toLowerCase().includes(q)||p.cat.toLowerCase().includes(q)));let s=document.getElementById('sort').value;if(s==='low')a.sort((x,y)=>x.price-y.price);if(s==='high')a.sort((x,y)=>y.price-x.price);document.getElementById('products').innerHTML=a.map(p=>`<article class="card"><button class="heart" onclick="toggleWish(${p.id})">${wish.includes(p.id)?'❤️':'🤍'}</button><div class="pic">${p.img?`<img src="${p.img}">`:p.emoji}</div><h3>${p.name}</h3><div class="price">৳${money(p.price)} <span class="old">৳${money(p.old)}</span></div><div class="stock">স্টক: ${money(p.stock)} টি</div><div class="buyrow"><button class="add" onclick="add(${p.id})">🛒 কার্টে</button><button class="buy" onclick="buyNow(${p.id})">এখনই কিনুন</button></div></article>`).join('')||'<p>কোনো পণ্য পাওয়া যায়নি।</p>'}
function saveCart(){localStorage.setItem('kp_cart',JSON.stringify(cart));updateCart()}function add(id){let x=cart.find(i=>i.id===id);if(x)x.qty++;else cart.push({id,qty:1});saveCart();openCart()}function buyNow(id){cart=[{id,qty:1}];saveCart();checkout()}
function updateCart(){document.getElementById('cartCount').textContent=money(cart.reduce((s,i)=>s+i.qty,0));let total=0;document.getElementById('cartItems').innerHTML=cart.map(i=>{let p=products.find(x=>x.id===i.id);total+=p.price*i.qty;return `<div class="drawerItem"><div><b>${p.name}</b><br>৳${money(p.price)} × ${i.qty}</div><div><button onclick="change(${p.id},-1)">−</button> <button onclick="change(${p.id},1)">+</button></div></div>`}).join('')||'<p>কার্ট খালি।</p>';document.getElementById('total').textContent=money(total)}function change(id,d){let x=cart.find(i=>i.id===id);if(!x)return;x.qty+=d;if(x.qty<=0)cart=cart.filter(i=>i.id!==id);saveCart()}function openCart(){document.getElementById('cart').classList.add('open');document.getElementById('shade').classList.add('show')}function closeCart(){document.getElementById('cart').classList.remove('open');document.getElementById('shade').classList.remove('show')}
function checkout(){if(!cart.length)return alert('আগে একটি পণ্য কার্টে যোগ করুন।');closeCart();let sel=document.getElementById('payment');sel.innerHTML=Object.entries(settings.payments).filter(([,v])=>v).map(([k])=>`<option>${k}</option>`).join('');updateManual();document.getElementById('payment').onchange=updateManual;checkoutDlg.showModal()}function updateManual(){let p=document.getElementById('payment').value;document.getElementById('manualPay').innerHTML=['bKash','Nagad','Rocket','Upay','Send Money'].includes(p)?'<b>ম্যানুয়াল পেমেন্ট:</b> আপনার ব্যবসার নম্বর/ব্যাংক তথ্য এখানে সেট করে দিতে হবে। টাকা পাঠানোর পর Transaction ID দিন।<label>Transaction ID<input id="trx" placeholder="যেমন: 8A7B6C"></label>':''}
function placeOrder(e){e.preventDefault();let order={id:'KP'+Date.now(),name:document.getElementById('name').value,phone:document.getElementById('phone').value,address:document.getElementById('address').value,payment:document.getElementById('payment').value,items:cart,total:cart.reduce((s,i)=>s+products.find(p=>p.id===i.id).price*i.qty,0),time:new Date().toLocaleString()};localStorage.setItem('kp_last_order',JSON.stringify(order));cart=[];saveCart();checkoutDlg.close();alert(`অর্ডার গ্রহণ করা হয়েছে!\nঅর্ডার নম্বর: ${order.id}`)}
function toggleWish(id){wish=wish.includes(id)?wish.filter(x=>x!==id):[...wish,id];localStorage.setItem('kp_wish',JSON.stringify(wish));render()}
function voiceSearch(){if(!('webkitSpeechRecognition'in window||'SpeechRecognition'in window))return alert('আপনার ব্রাউজারে Voice Search সমর্থিত নয়।');let R=window.SpeechRecognition||window.webkitSpeechRecognition;let r=new R();r.lang='bn-BD';r.onresult=e=>{document.getElementById('search').value=e.results[0][0].transcript;render()};r.start()}
function openAdmin(){['setName','setSlogan','setLogo','setHero','setHeroText'].forEach((id,i)=>document.getElementById(id).value=[settings.name,settings.slogan,settings.logo,settings.hero,settings.heroText][i]);document.getElementById('payChecks').innerHTML=Object.keys(settings.payments).map(k=>`<label><input type="checkbox" id="pay_${k}" ${settings.payments[k]?'checked':''}> ${k}</label>`).join('');adminDlg.showModal()}function saveSettings(){settings.name=document.getElementById('setName').value||defaultSettings.name;settings.slogan=document.getElementById('setSlogan').value;settings.logo=document.getElementById('setLogo').value;settings.hero=document.getElementById('setHero').value;settings.heroText=document.getElementById('setHeroText').value;Object.keys(settings.payments).forEach(k=>settings.payments[k]=document.getElementById('pay_'+k).checked);localStorage.setItem('kp_settings',JSON.stringify(settings));adminDlg.close();init()}
document.getElementById('search').addEventListener('input',render);init();
